/*
Create data column for google syncing
*/
ALTER TABLE User ADD COLUMN isFromGoogle BOOLEAN DEFAULT FALSE;
ALTER TABLE User ADD COLUMN isAutoSync BOOLEAN DEFAULT FALSE;
ALTER TABLE User ADD COLUMN adminEmail TEXT;
ALTER TABLE User ADD COLUMN isSyncAdmin BOOLEAN DEFAULT FALSE;
ALTER TABLE User ADD COLUMN syncAdmin CHAR(36);
ALTER TABLE User ADD COLUMN isSyncActivated BOOLEAN DEFAULT FALSE;

